name: GardensSprouter
version: 1.0.0
author: Bright_Steel
main: com.gardensmc.sprouter.spigot.SprouterSpigot
api-version: 1.20
commands:
  nickname:
    description: Change player's display name
    usage: /<command> <nickname> [player]
    aliases: ['nick']
  gamemode:
    description: Change player's game mode
    usage: /<command> <gamemode> [player]
    aliases: ['gm']
  fly:
    description: Toggle player's fly mode
    usage: /<command> [on|off] [player]
  me:
    description: Describe what you are doing
    usage: /<command> <message>
  message:
    description: Message another player
    usage: /<command> <message>
    aliases: ['msg', 'm']
  tpa:
    description: Send a teleport request to another player
    usage: /<command> <player>
  tpahere:
    description: Send a request to teleport a player to you
    usage: /<command> <player>
  tp:
    description: Teleport to another player, or teleport a player to another player
    usage: /<command> <player> [player]
  tphere:
    description: Teleport another player to you
    usage: /<command> <player>
  tppos:
    description: Teleport to a specified position
    usage: /<command> <x> <y> <y> [yaw] [pitch] [world]